spring:
  # 기본 데이터소스 (Primary)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accrunnerdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # Dialect는 Spring Boot가 DataSource를 보고 자동으로 감지하므로, 명시하지 않아도 됨
        # dialect: org.hibernate.dialect.H2Dialect

  # Batch 설정
  batch:
    jdbc:
      initialize-schema: always

# 대상 데이터소스 (Secondary)
db:
  datasources:
    anasa-db:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:sqlserver://sql16ssd-008.localnet.kr:1433;databaseName=anasa1_daon;encrypt=true;trustServerCertificate=true
      username: anasa1_daon
      password: anasa@425

# Log4jdbc를 사용하기 위한 설정
log4jdbc:
  spylogdelegator:
    name: net.sf.log4j2.log.slf4j.Slf4jSpyLogDelegator